- name: add ssh key for ansi client
  authorized_key:
    user: ansigent
    key: "{{ item }}"
  with_file:
    - ~/.ssh/ansible.pub

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: /roles/base/templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd