- name: create AWX namespace
  k8s:
    name: awx
    api_version: v1
    kind: Namespace
    state: present

- name: install AWX
  k8s:
    src: ~/hp-automation/ansible/files/awx-operator.yaml
    namespace: awx
    state: present

- name: create AWX deployment
  k8s:
    definition:
      apiVersion: awx.ansible.com/v1beta1
      kind: AWX
      metadata:
        name: awx
      spec:
        service_type: nodeport
        ingress_type: none
        hostname: awx.example.com
    namespace: awx
    state: present

# - name: expose AWX service
#   become_user: ansiadmin
#   k8s_service:
#     name: awx
#     namespace: awx
#     ports:
#     - port: 8080
#       protocol: TCP
#     type: LoadBalancer
#     selector:
#       name: awx
#     state: absent

