- name: install prerequesite packages
  apt: 
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - nano
    - wget
    - git
    - python3-pip
    - net-tools

# install docker engine
- name: install dependencies (Docker)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: add GPG key (Docker)
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: add repository (Docker)
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: install Docker
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  notify: restart_docker

- name: install docker-python module
  pip:
    name: docker
    
# install mongodb
- name: install mongodb docker
  docker_container:
    name: mongodb
    image: mongo:4.4.6
    auto_remove: true
    state: started
    ports:
      - "27017:27017"
    volumes:
      - MongoDockerData:/data/db

      
# - name: add repository (libssl 1.1)
#   apt_repository:
#     repo: "deb http://security.ubuntu.com/ubuntu focal-security main"
#     filename: /etc/apt/sources.list.d/focal-security
#   when: ansible_distribution_version == "22.04"

# - name: install libssl 1.1
#   apt:
#     name: libssl1.1
#     update_cache: yes
#   when: ansible_distribution_version == "22.04"

# - name: remove repository (libssl 1.1)
#   apt_repository:
#     repo: "deb http://security.ubuntu.com/ubuntu focal-security main"
#     state: absent
#     filename: /etc/apt/sources.list.d/focal-security
#   when: ansible_distribution_version == "22.04"

# - name: add PGP key (MongoDB)
#   apt_key: 
#     url: https://www.mongodb.org/static/pgp/server-5.0.asc
  
# - name: add repository (MongoDB)
#   apt_repository:
#     repo: "deb https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse"
#     filename: /etc/apt/sources.list.d/mongodb-org-5.0

# - name: install MongoDB
#   apt:
#     name: mongodb-org
#     state: latest
#     update_cache: yes
#   notify: restart_mongodb