- name: install prerequesite packages
  apt:
      name:
          [
              "curl",
              "nano",
              "wget",
              "git",
              "python3-pip",
              "net-tools",
              "qemu-user-static",
          ]
      state: latest
  async: 3600
  poll: 0

# QEMU installation
- name: check QEMU status
  command: cat /proc/sys/fs/binfmt_misc/status
  async: 3600
  poll: 0
  register: qemu_status

- name: activate QEMU when disabled
  command: mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc
  async: 3600
  poll: 0
  when: qemu_status.stdout != "enabled"

- name: register QEMU interpreters
  command: "{{ item }}"
  with_items:
      - update-binfmts --enable qemu-arm
      - update-binfmts --enable qemu-aarch64
      - update-binfmts --enable qemu-ppc64le
      - update-binfmts --enable qemu-mips64
      - update-binfmts --enable qemu-mips64el
      - update-binfmts --enable qemu-mips
      - update-binfmts --enable qemu-mipsel
      - update-binfmts --enable qemu-s390x
  ignore_errors: true
  async: 3600
  poll: 0

# install docker engine
- name: install dependencies (Docker)
  apt:
      name:
          [
              "apt-transport-https",
              "ca-certificates",
              "gnupg-agent",
              "software-properties-common",
          ]
      state: present

- name: add GPG key (Docker)
  apt_key:
      url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
      state: present

- name: add repository (Docker)
  apt_repository:
      repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
      state: present

- name: install Docker
  apt:
      name: ["docker-ce", "docker-ce-cli", "containerd.io"]
      state: latest
  notify: restart_docker

- name: install python module
  pip:
      name: [docker, urllib3==1.26.5]

# install mongodb
- name: install mongodb docker
  docker_container:
      name: mongodb
      image: mongo:4.4.6
      auto_remove: true
      state: started
      ports:
          - "27017:27017"
      volumes:
          - MongoDockerData:/data/db
  async: 3600
  poll: 0

- name: install psycopg2 module
  pip:
      name: psycopg2-binary
