- name: create AWX namespace
  k8s:
    name: postgres
    api_version: v1
    kind: Namespace
    state: present 

- name: install postgres configmap
  k8s:
    definition: "{{ lookup('template', '~/hp-automation/ansible/roles/postgres/templates/postgres-config.j2') | from_yaml }}"
    namespace: postgres
    state: present

- name: install postgres
  k8s:
    src: ~/hp-automation/ansible/files/postgres.yaml
    namespace: postgres
    state: present