- name: create ansiadmin user
  user:
    name: ansiadmin
    password: $1$SomeSalt$d3heDLqN0l.9QW2PgDOXH/
    shell: /bin/bash

- name: install packages
  apt: 
    name: ['net-tools', 'lynx', 'docker.io']
    state: latest

- name: install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: "755"

- name: install minikube
  get_url:
    url: https://github.com/kubernetes/minikube/releases/download/v1.21.0/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: "755"

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present
    
- name: add user to docker group
  user:
    name: ansiadmin
    group: docker

- name: start minikube
  command: runuser -l ansiadmin -c 'minikube start --addons=ingress --cpus=2 --install-addons=true --kubernetes-version=stable'

