- name: install packages
  apt: 
    name: "{{ item }}"
    state: latest
  with_items:
    - net-tools
    - lynx
    - docker.io

- name: install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: "755"

- name: install minikube
  get_url:
    url: https://github.com/kubernetes/minikube/releases/download/v1.21.0/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: "755"

- name: add user to docker group
  user:
    name: "{{ ansible_env.USER }}"
    group: docker

- name: start minikube
  command: minikube start
  args:
    - addons: ingress
    - cpus: 2
    - install-addons: true
    - kubernetes-version: stable
    - memory: 6g
