- name: create ansiadmin user
  user:
    name: ansiadmin
    password: $1$SomeSalt$d3heDLqN0l.9QW2PgDOXH/
    shell: /bin/bash

- name: add ssh key for ansiadmin
  authorized_key:
    user: ansiadmin
    key: "{{ item }}"
  with_file:
    - ~/.ssh/ansible.pub

- name: change /usr/local/bin permission
  file:
    path: /usr/local/bin/
    owner: ansiadmin
    # group: ansiadmin
    mode: '0766'

- name: install packages
  apt: 
    name: ['net-tools', 'lynx', 'docker.io', 'acl', 'python3-pip']
    state: present
  notify: 
    - restart_docker
    - restart_containerd

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present
    
- name: add user to docker group
  user:
    name: ansiadmin
    group: docker

- name: git clone
  git:
    repo: https://github.com/noctislucius20/hp-automation.git
    dest: /home/ansiadmin/hp-automation
    version: dev-autodeploy