- name: run rdpy docker image
  docker_container:
    name: rdpy
    image: isif/rdpy:rdpy_hp
    ports: 
      - 3389:3389
    volumes:
      - rdpy:/var/log
    tty: true
    interactive: true
    detach: true
    state: started
    command: /bin/bash -c "python /rdpy/bin/rdpy-rdphoneypot.py -l 3389 /rdpy/bin/1 >> /var/log/rdpy.log"
  register: testtt

- name: output
  debug: 
    msg: "{{ testtt }}"

# - name: dasddasd
#   community.docker.docker_container_exec:
#     container: "{{ testtt.container.Config.Hostname }}"
#     command: /bin/bash -c "python /rdpy/bin/rdpy-rdphoneypot.py -l 3389 /rdpy/bin/1 >> /var/log/rdpy.log"
#     detach: true