---
- hosts: "{{ ip_address }}"
  gather_facts: false
  become: true
  pre_tasks:
      - name: install updates
        apt:
            upgrade: dist
            update_cache: yes

- hosts: " {{ ip_address }}"
  gather_facts: false
  become: true
  roles:
      - base
  tags: [honeypot]
