---
- hosts: workstation_deploy
  become: true
  tasks:
  - name: update repo cache
    apt:
      update_cache: yes
    changed_when: false

  - name: git clone
    git:
        repo: https://github.com/noctislucius20/hp-automation.git
        dest: /home/ansiadmin/hp-automation
        version: master
  
  - name: disable swap
    command: swapoff -a && sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
      
- hosts: workstation_deploy
  roles:
    - minikube
    - awx
    - postgres
    - elk
    - filebeat
  tags: [ workstation ]