---
- hosts: "{{ ip_address }}"
  become: true
  gather_facts: false
  pre_tasks:
      - name: set ansible_port
        set_fact:
            ansible_port: 22888

      - name: update repo cache
        apt:
            update_cache: yes
        changed_when: false

- hosts: "{{ ip_address }}"
  gather_facts: true
  become: true
  roles:
      - package
  tags: [honeypot]
