---
- hosts: "{{ ip_address }}"
  become: true
  gather_facts: false
  pre_tasks:
      - name: set ansible_port
        set_fact:
            ansible_port: 22888

      - name: set installed honeypot
        set_fact:
            honeypot_list: "{{ hp_list }}"

- hosts: "{{ ip_address }}"
  become: true
  gather_facts: false
  roles:
      - role: rdpy
        when: honeypot_list is search("rdpy")
  tags: [honeypot]

# when honeypot is not selected
- hosts: "{{ ip_address }}"
  gather_facts: false
  become: true
  tasks:
      - name: stop rdpy docker image
        docker_container:
            name: rdpy
            state: stopped
        when: not honeypot_list is search("rdpy")
  tags: [honeypot]
