---
- hosts: "{{ ip_address }}"
  become: true
  gather_facts: false
  pre_tasks:
      - name: set ansible_port
        set_fact:
            ansible_port: 22888

- hosts: "{{ ip_address }}"
  become: true
  roles:
      - dionaea
  tags: [honeypot]
