---
- hosts: "{{ ip_address }}"
  become: true
  gather_facts: false
  pre_tasks:
      - name: set ansible_port
        set_fact:
            ansible_port: 22888

      - name: set installed honeypot
        set_fact:
            honeypot_list: "{{ hp_list }}"

- hosts: "{{ ip_address }}"
  become: true
  gather_facts: false
  tasks:
      - name: checking cowrie opened ports
        plugin: community.general.nmap
        address: "{{ ip_address }}/32"
        port: 22
        when: honeypot_list is search("cowrie")
