---
- hosts: "{{ ip_address }}"
  become: true
  gather_facts: false
  pre_tasks:
      - name: set ansible_port
        set_fact:
            ansible_port: 22888

      - name: set installed honeypot
        set_fact:
            honeypot_list: "{{ hp_list }}"

- hosts: "{{ ip_address }}"
  become: true
  gather_facts: false
  tasks:
      - name: checking cowrie opened ports
        wait_for:
            host: "{{ ip_address }}"
            port: 22
            state: started
            timeout: 4
        async: 60
        poll: 0
        when: honeypot_list is search("cowrie")

      - name: checking dionaea opened ports
        wait_for:
            host: "{{ ip_address }}"
            port: 21
            state: started
            timeout: 1
        async: 60
        poll: 0
        when: honeypot_list is search("dionaea")

      - name: checking elasticpot opened ports
        wait_for:
            host: "{{ ip_address }}"
            port: 9200
            state: started
            timeout: 1
        async: 60
        poll: 0
        when: honeypot_list is search("elasticpot")

      - name: checking gridpot opened ports
        wait_for:
            host: "{{ ip_address }}"
            port: 8000
            state: started
            timeout: 1
        async: 60
        poll: 0
        when: honeypot_list is search("gridpot")

      - name: checking honeytrap opened ports
        wait_for:
            host: "{{ ip_address }}"
            port: 631
            state: started
            timeout: 1
        async: 60
        poll: 0
        when: honeypot_list is search("honeytrap")

      - name: checking rdpy opened ports
        wait_for:
            host: "{{ ip_address }}"
            port: 3389
            state: started
            timeout: 1
        async: 60
        poll: 0
        when: honeypot_list is search("rdpy")
