---
- hosts: honeypot_servers
  become: true
  pre_tasks:
    - name: set ansible_port
      set_fact:
        ansible_port: 22888

- hosts: honeypot_servers
  become: true
  roles:
    - gridpot
  tags: [ honeypot ]