---
- hosts: "{{ ip_address }}"
  become: true
  gather_facts: false
  pre_tasks:
      - name: set ansible_port
        set_fact:
            ansible_port: 22888
  when: ansible_run_tags == "honeypot"
  # tags: [honeypot]

- hosts: "{{ ip_address }}"
  become: true
  roles:
      - cowrie
  when: ansible_run_tags == "cowrie"
  # tags: [cowrie]

- hosts: "{{ ip_address }}"
  become: true
  roles:
      - dionaea
  tags: [dionaea]

- hosts: "{{ ip_address }}"
  become: true
  roles:
      - elasticpot
  tags: [elasticpot]

- hosts: "{{ ip_address }}"
  become: true
  roles:
      - gridpot
  tags: [gridpot]

- hosts: "{{ ip_address }}"
  become: true
  roles:
      - honeytrap
  tags: [honeytrap]

- hosts: "{{ ip_address }}"
  become: true
  roles:
      - rdpy
  tags: [rdpy]
