---

- hosts: honeypot_servers
  become: true
  remote_user: ansigent
  gather_facts: false
  pre_tasks:
    - name: set ansible_port
      set_fact:
        ansible_port: 22888

    - name: update repo cache
      apt:
        update_cache: yes
      changed_when: false
  
- hosts: honeypot_servers
  remote_user: ansigent
  become: true
  roles:
    - base
  tags: [ honeypot ]

- hosts: honeypot_servers
  remote_user: ansigent
  become: true
  roles:
    - package
    - cowrie
    - dionaea
    - honeytrap
    - rdpy
    - gridpot
    - elasticpot
    - ewsposter
  tags: [ honeypot ]