"""add table honeypotdetail

Revision ID: 2476d9220460
Revises: 4721bbba0040
Create Date: 2023-03-06 23:34:56.553943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2476d9220460'
down_revision = '4721bbba0040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('honeypot_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('honeypot_sensor_id', sa.Integer(), nullable=False),
    sa.Column('sensor_name', sa.String(), nullable=False),
    sa.Column('honeypot_name', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('sleeping', 'not running', 'running', name='honeypotdetail_state_enum'), nullable=False),
    sa.Column('virtual_memory', sa.Float(), nullable=False),
    sa.Column('resident_memory', sa.Float(), nullable=False),
    sa.Column('text_memory', sa.Float(), nullable=False),
    sa.Column('data_memory', sa.Float(), nullable=False),
    sa.Column('virtual_memory_percentage', sa.Float(), nullable=False),
    sa.Column('resident_memory_percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['honeypot_sensor_id'], ['honeypot_sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('honeypot_details')
    # ### end Alembic commands ###
