"""add table authentications

Revision ID: 27a1b0c29632
Revises: 84057b391203
Create Date: 2023-03-06 22:30:48.771697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a1b0c29632'
down_revision = '84057b391203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentications',
    sa.Column('token', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authentications')
    # ### end Alembic commands ###
