"""modify honeypot name to unique

Revision ID: 32a5519445e3
Revises: cbbcbf0770c2
Create Date: 2023-03-23 22:54:59.258218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a5519445e3'
down_revision = 'cbbcbf0770c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('honeypots', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('honeypots', schema=None) as batch_op:
        batch_op.drop_constraint('honeypots_name_key', type_='unique')

    # ### end Alembic commands ###
