"""move state column from sensor to sensordetail

Revision ID: 87ca9467f629
Revises: bc951c24520c
Create Date: 2023-03-21 20:40:50.401868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ca9467f629'
down_revision = 'bc951c24520c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Boolean(), nullable=False))

    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('sensor_details', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
