"""add table sensordetail

Revision ID: 8d9468e700c9
Revises: 2476d9220460
Create Date: 2023-03-06 23:56:35.179560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9468e700c9'
down_revision = 'ea7a20483456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('sensor_name', sa.String(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('honeypot_running', sa.Integer(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('cpu_frequency', sa.Float(), nullable=False),
    sa.Column('cpu_count', sa.Integer(), nullable=False),
    sa.Column('ram_total', sa.Float(), nullable=False),
    sa.Column('ram_usage', sa.Float(), nullable=False),
    sa.Column('ram_available', sa.Float(), nullable=False),
    sa.Column('ram_percentage', sa.Float(), nullable=False),
    sa.Column('swap_memory_total', sa.Float(), nullable=False),
    sa.Column('swap_memory_usage', sa.Float(), nullable=False),
    sa.Column('swap_memory_free', sa.Float(), nullable=False),
    sa.Column('swap_memory_percentage', sa.Float(), nullable=False),
    sa.Column('network_packet_received', sa.Integer(), nullable=False),
    sa.Column('network_packet_sent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_details')
    # ### end Alembic commands ###
