"""add table history, status code

Revision ID: ac9fa568e89c
Revises: 32a5519445e3
Create Date: 2023-04-12 23:51:09.658523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9fa568e89c'
down_revision = '2476d9220460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('honeypot_sensor_id', sa.Integer(), nullable=False),
    sa.Column('sensor_status', sa.String(), nullable=False),
    sa.Column('honeypot_status', sa.String(), nullable=False),
    sa.Column('status_code_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('threat_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resident_memory_size', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['status_code_id'], ['status_codes.id'], ),
    sa.ForeignKeyConstraint(['honeypot_sensor_id'], ['honeypot_sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('status_codes')
    # ### end Alembic commands ###
