"""change honeypotdetail state datatype to varchar

Revision ID: d081f25e6fd4
Revises: 87ca9467f629
Create Date: 2023-03-21 20:47:28.514599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd081f25e6fd4'
down_revision = '87ca9467f629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('honeypot_details', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=postgresql.ENUM('sleeping', 'not running', 'running', name='honeypotdetail_state_enum'),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('honeypot_details', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.String(),
               type_=postgresql.ENUM('sleeping', 'not running', 'running', name='honeypotdetail_state_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###
